const content = [
  {
    keyword: ["anakin nut"],
    gif: ["https://i.redd.it/apzz3qxbpf801.jpg"],
    voiceLine: [null],
  },
  {
    keyword: ["yoda nut"],
    gif: ["https://tenor.com/view/nutted-sucking-yoda-star-wars-gif-4955543"],
    voiceLine: [null],
  },
  {
    keyword: ["anakin"],
    gif: [
      "https://tenor.com/view/star-wars-anakin-skywalker-what-have-idone-confused-sad-gif-3575836",
      "https://tenor.com/view/sw-starwars-anakin-anakinskywalker-stunning-gif-4830485",
      "https://tenor.com/view/anakin-star-wars-fun-begin-smile-gif-7220749",
      "https://tenor.com/view/hate-you-anakin-gif-5247878",
      "https://tenor.com/view/star-wars-ihate-them-mad-angry-anakin-skywalker-gif-3580805",
      "https://media.giphy.com/media/gtBDviunS4OCA/giphy.gif",
      "https://media.giphy.com/media/mE33kDd1A6LPW/giphy.gif",
      "https://media.giphy.com/media/3owzWn24wYQndbQmyY/giphy.gif",
    ],
    voiceLine: [
      "./sound-effects/anakin/its-working.mp4",
      "./sound-effects/anakin/enter-my-pod.mp3",
      "./sound-effects/anakin/this-is-tense.mp3",
      "./sound-effects/anakin/cold-sir.mp3",
      "./sound-effects/anakin/angel.mp3",
      "./sound-effects/anakin/podracing.mp3",
      "./sound-effects/anakin/spinning.mp3",
      "./sound-effects/anakin/so-wizard.mp3",
      "./sound-effects/anakin/pilot.mp3",
      "./sound-effects/anakin/person.mp3",
      "./sound-effects/anakin/against-me.mp3",
      "./sound-effects/anakin/bad-feeling.mp3",
      "./sound-effects/anakin/buzz-droids.mp3",
      "./sound-effects/anakin/destroyers.mp3",
      "./sound-effects/anakin/fun-begins.mp3",
      "./sound-effects/anakin/i-hate-you.mp3",
      "./sound-effects/anakin/i-killed-them.mp3",
      "./sound-effects/anakin/intoxicating.mp3",
      "./sound-effects/anakin/jealous.mp3",
      "./sound-effects/anakin/kill-you.mp3",
      "./sound-effects/anakin/liar.mp3",
      "./sound-effects/anakin/new-powers.mp3",
      "./sound-effects/anakin/no.mp3",
      "./sound-effects/anakin/not-fair.mp3",
      "./sound-effects/anakin/pledge-myself.mp3",
      "./sound-effects/anakin/sand.mp3",
      "./sound-effects/anakin/so-beautiful.mp3",
      "./sound-effects/anakin/speeder.mp3",
      "./sound-effects/anakin/stand-trial.mp3",
      "./sound-effects/anakin/take-her-from-me.mp3",
      "./sound-effects/anakin/too-many.mp3",
      "./sound-effects/anakin/unfair.mp3",
      "./sound-effects/anakin/you-will-try.mp3",
      "./sound-effects/anakin/what-have-i-done.mp3",
      "./sound-effects/obi-won/underestimate-my-power.mp3",
    ],
  },
  {
    keyword: ["yoda"],
    gif: [
      "https://tenor.com/view/yoda-gif-11875428",
      "https://tenor.com/view/yoda-star-wars-gif-11754851",
      "https://tenor.com/view/yoda-what-you-say-are-you-serious-are-you-stupid-are-you-dumb-gif-5892155",
      "https://tenor.com/view/chile-yoda-creepy-weird-luke-skywalker-gif-8844889",
    ],
    voiceLine: [
      "./sound-effects/yoda/suffering.mp3",
      "./sound-effects/yoda/death-sound.mp3",
      "./sound-effects/yoda/very-good.mp3",
    ],
  },
  {
    keyword: ["palp"],
    gif: [
      "https://tenor.com/view/star-wars-emperor-chancellor-palpatine-gif-8128416",
      "https://tenor.com/view/palpatine-gif-13095906",
      "https://tenor.com/view/sheev-palpatine-emperor-chancellor-kill-him-now-gif-14424446",
      "https://tenor.com/view/good-palpatine-gif-8789828",
      "https://tenor.com/view/no-emperor-palpatine-gif-13110787",
      "https://tenor.com/view/star-wars-palpatine-senate-gif-13095904",
    ],
    voiceLine: [
      "./sound-effects/palpatine/deformed.mp3",
      "./sound-effects/palpatine/do-it.mp3",
      "./sound-effects/palpatine/feel-your-anger.mp3",
      "./sound-effects/palpatine/good.mp3",
      "./sound-effects/palpatine/grunt.mp3",
      "./sound-effects/palpatine/i-am-the-senate.mp3",
      "./sound-effects/palpatine/ironic.mp3",
      "./sound-effects/palpatine/kill-him.mp3",
      "./sound-effects/palpatine/kill-me.mp3",
      "./sound-effects/palpatine/no-no.mp3",
      "./sound-effects/palpatine/not-from-a-jedi.mp3",
      "./sound-effects/palpatine/once-more.mp3",
      "./sound-effects/palpatine/only-natural.mp3",
      "./sound-effects/palpatine/order.mp3",
      "./sound-effects/palpatine/taking-over.mp3",
      "./sound-effects/palpatine/too-weak.mp3",
      "./sound-effects/palpatine/too-weak-1.mp3",
      "./sound-effects/palpatine/tragedy.mp3",
      "./sound-effects/palpatine/treason.mp3",
      "./sound-effects/palpatine/unlimited-power.mp3",
    ],
  },
  {
    keyword: ["padme"],
    gif: [
      "https://tenor.com/view/sw-starwars-anakin-anakinskywalker-stunning-gif-4830485",
    ],
    voiceLine: [
      "./sound-effects/padme/suffer-and-die.mp3",
      "./sound-effects/padme/breaking-my-heart.mp3",
      "./sound-effects/padme/liberty-dies.mp3",
      "./sound-effects/padme/youve-grown.mp3",
    ],
  },
  {
    keyword: ["mace"],
    gif: [null],
    voiceLine: [
      "./sound-effects/mace-windu/party-over.mp3",
      "./sound-effects/mace-windu/sith-lord.mp3",
      "./sound-effects/mace-windu/take-a-seat.mp3",
      "./sound-effects/mace-windu/think-so.mp3",
      "./sound-effects/mace-windu/under-arrest.mp3",
    ],
  },
  {
    keyword: ["dooku"],
    gif: [null],
    voiceLine: [
      "./sound-effects/count-dooku/double-the-fall.mp3",
      "./sound-effects/count-dooku/great-fear.mp3",
    ],
  },
  {
    keyword: ["greivous"],
    gif: [null],
    voiceLine: [
      "./sound-effects/greivous/doomed.mp3",
      "./sound-effects/greivous/fine-addition.mp3",
      "./sound-effects/greivous/general-kenobi.mp3",
      "./sound-effects/greivous/jedi-scum.mp3",
      "./sound-effects/greivous/negotiator.mp3",
      "./sound-effects/greivous/ray-shields.mp3",
      "./sound-effects/greivous/you-fool.mp3",
    ],
  },
  {
    keyword: ["obi won"],
    gif: [null],
    voiceLine: [
      "./sound-effects/obi-won/negotiations.mp3",
      "./sound-effects/obi-won/absolutes.mp3",
      "./sound-effects/obi-won/always-on-the-move.mp3",
      "./sound-effects/obi-won/archives-are-incomplete.mp3",
      "./sound-effects/obi-won/bad-feeling-about-this.mp3",
      "./sound-effects/obi-won/chosen-one.mp3",
      "./sound-effects/obi-won/death-sticks.mp3",
      "./sound-effects/obi-won/easy.mp3",
      "./sound-effects/obi-won/hate-it.mp3",
      "./sound-effects/obi-won/hello-there.mp3",
      "./sound-effects/obi-won/high-ground.mp3",
      "./sound-effects/obi-won/like-it.mp3",
      "./sound-effects/obi-won/pull-up.mp3",
      "./sound-effects/obi-won/sith-lords.mp3",
      "./sound-effects/obi-won/so-uncivilized.mp3",
      "./sound-effects/obi-won/sweating.mp3",
      "./sound-effects/obi-won/together.mp3",
      "./sound-effects/obi-won/find-us.mp3",
      "./sound-effects/obi-won/good-job.mp3",
      "./sound-effects/obi-won/another-happy-landing.mp3",
    ],
  },
  {
    keyword: ["trade"],
    gif: [null],
    voiceLine: [
      "./sound-effects/trade-federation/all-batteries-fire.mp3",
      "./sound-effects/trade-federation/coming-through.mp3",
      "./sound-effects/trade-federation/droidekas.mp3",
      "./sound-effects/trade-federation/magnetize.mp3",
      "./sound-effects/trade-federation/promised-peace.mp3",
      "./sound-effects/trade-federation/shoot-her.mp3",
      "./sound-effects/trade-federation/victory.mp3",
    ],
  },
  {
    keyword: "jar jar",
    gif: [
      "https://i.gifer.com/FVtT.gif",
      "https://i.gifer.com/AeXc.gif",
      "https://i.gifer.com/1DvB.gif",
      "https://i.gifer.com/HoFv.gif",
      "https://i.gifer.com/A6A8.gif",
      "https://i.gifer.com/A6A6.gif",
      "https://i.gifer.com/FVtb.gif",
      "https://i.gifer.com/DIjo.gif",
      "https://media.giphy.com/media/3owzWdDuy7KiZLKpy0/giphy.gif",
      "https://media.giphy.com/media/3owzVXxFgjfDpQ3fPy/giphy.gif",
      "https://media.giphy.com/media/3owzVQch8fzfptlES4/giphy.gif",
    ],
    voiceLine: [
      "./sound-effects/jar-jar/ah-hah.mp3",
      "./sound-effects/jar-jar/big-goober-fish.mp3",
      "./sound-effects/jar-jar/boom.mp3",
      "./sound-effects/jar-jar/exqueeze-me.mp3",
      "./sound-effects/jar-jar/hello-boyos.mp3",
      "./sound-effects/jar-jar/how-wude.mp3",
      "./sound-effects/jar-jar/i-spek.mp3",
      "./sound-effects/jar-jar/jump-jar-jar.mp3",
      "./sound-effects/jar-jar/maxi-big.mp3",
      "./sound-effects/jar-jar/meesa-back.mp3",
      "./sound-effects/jar-jar/meesa-jar-jar-binks.mp3",
      "./sound-effects/jar-jar/messa-like-dis.mp3",
      "./sound-effects/jar-jar/muy-muy.mp3",
      "./sound-effects/jar-jar/my-give-up.mp3",
      "./sound-effects/jar-jar/pee-yousa.mp3",
      "./sound-effects/jar-jar/saved-my-again.mp3",
      "./sound-effects/jar-jar/steady.mp3",
      "./sound-effects/jar-jar/stinkywhiff.mp3",
      "./sound-effects/jar-jar/very-bad.mp3",
      "./sound-effects/jar-jar/whosa-are-yousa.mp3",
      "./sound-effects/jar-jar/yelling.mp3",
      "./sound-effects/jar-jar/your-honor.mp3",
      "./sound-effects/jar-jar/bustin-with-happiness.mp3",
      "./sound-effects/jar-jar/looky-looky.mp3",
      "./sound-effects/jar-jar/so-smiling.mp3",
    ],
  },
  {
    keyword: ["victory"],
    gif: [null],
    voiceLine: ["./sound-effects/trade-federation/victory.mp3"],
  },
  {
    keyword: ["coming through"],
    gif: [null],
    voiceLine: ["./sound-effects/trade-federation/coming-through.mp3"],
  },
  {
    keyword: ["droidekas"],
    gif: [null],
    voiceLine: ["./sound-effects/trade-federation/droidekas.mp3"],
  },

  {
    keyword: ["working"],
    gif: ["https://tenor.com/view/working-anakin-starwars-gif-4653092"],
    voiceLine: ["./sound-effects/its-working.mp4"],
  },
  {
    keyword: ["die"],
    gif: ["https://tenor.com/view/no-emperor-palpatine-gif-13110787"],
    voiceLine: ["./sound-effects/palpatine/no-no.mp3"],
  },
  {
    keyword: ["good"],
    gif: ["https://media.giphy.com/media/xTiIzL9Btjx9hegHT2/giphy.gif"],
    voiceLine: ["./sound-effects/palpatine/good.mp3"],
  },
  {
    keyword: ["try it"],
    gif: ["https://media.giphy.com/media/pHB2cl3wCGlKU/giphy.gif"],
    voiceLine: [null],
  },
  {
    keyword: ["podracing"],
    gif: [null],
    voiceLine: ["./sound-effects/anakin/podracing.mp3"],
  },
  {
    keyword: ["love"],
    gif: ["https://i.redd.it/3dmk63noigj11.gif"],
    voiceLine: [null],
  },
  {
    keyword: ["wizard"],
    gif: ["https://media.giphy.com/media/26wBbEx3MpDeDZcZ2/giphy.gif"],
    voiceLine: ["./sound-effects/anakin/so-wizard.mp3"],
  },
  {
    keyword: ["sand"],
    gif: [
      "https://tenor.com/view/anakin-sand-skywalker-anakin-skywalker-star-wars-gif-13723718",
    ],
    voiceLine: ["./sound-effects/anakin/sand.mp3"],
  },
  {
    keyword: ["liar"],
    gif: ["https://tenor.com/view/anakin-liar-starwars-gif-8634649"],
    voiceLine: ["./sound-effects/anakin/liar.mp3"],
  },
  {
    keyword: ["fair"],
    gif: ["https://media.giphy.com/media/3ohuAsQcmrk3c8XgMU/giphy.gif"],
    voiceLine: ["./sound-effects/anakin/not-fair.mp3"],
  },
  {
    keyword: ["high"],
    gif: ["https://media2.giphy.com/media/j0IAyUkwpEQg0/giphy.gif"],
    voiceLine: ["./sound-effects/obi-won/high-ground.mp3"],
  },
  {
    keyword: ["cold"],
    gif: ["https://media.giphy.com/media/HUVhRiUpOre6I/giphy.gif"],
    voiceLine: ["./sound-effects/anakin/cold-sir.mp3"],
  },
  {
    keyword: ["weak"],
    gif: [
      "https://tenor.com/view/sheev-palpatine-star-wars-icant-hold-it-any-longer-gif-14622258",
    ],
    voiceLine: ["./sound-effects/palpatine/too-weak.mp3"],
  },
  {
    keyword: ["hate"],
    gif: [null],
    voiceLine: ["./sound-effects/anakin/i-hate-you.mp3"],
  },
  {
    keyword: ["senate"],
    gif: ["https://tenor.com/view/star-wars-palpatine-senate-gif-13095904"],
    voiceLine: ["./sound-effects/palpatine/i-am-the-senate.mp3"],
  },
  {
    keyword: ["hi"],
    gif: [
      "https://tenor.com/view/star-wars-jarjar-binks-hello-boyos-hi-gif-11857957",
    ],
    voiceLine: ["./sound-effects/jar-jar/hello-boyos.mp3"],
  },
  {
    keyword: ["no"],
    gif: [null],
    voiceLine: ["./sound-effects/anakin/no.mp3"],
  },
  {
    keyword: ["tragedy"],
    gif: ["https://media.giphy.com/media/xTiIzxQye2bRk11qdG/giphy.gif"],
    voiceLine: ["./sound-effects/palpatine/tragedy.mp3"],
  },
  {
    keyword: ["random"],
    gif: [null],
    voiceLine: [
      "./sound-effects/anakin/its-working.mp4",
      "./sound-effects/anakin/enter-my-pod.mp3",
      "./sound-effects/anakin/this-is-tense.mp3",
      "./sound-effects/anakin/cold-sir.mp3",
      "./sound-effects/anakin/angel.mp3",
      "./sound-effects/anakin/podracing.mp3",
      "./sound-effects/anakin/spinning.mp3",
      "./sound-effects/anakin/so-wizard.mp3",
      "./sound-effects/anakin/pilot.mp3",
      "./sound-effects/anakin/person.mp3",
      "./sound-effects/anakin/against-me.mp3",
      "./sound-effects/anakin/bad-feeling.mp3",
      "./sound-effects/anakin/buzz-droids.mp3",
      "./sound-effects/anakin/destroyers.mp3",
      "./sound-effects/anakin/fun-begins.mp3",
      "./sound-effects/anakin/i-hate-you.mp3",
      "./sound-effects/anakin/i-killed-them.mp3",
      "./sound-effects/anakin/intoxicating.mp3",
      "./sound-effects/anakin/jealous.mp3",
      "./sound-effects/anakin/kill-you.mp3",
      "./sound-effects/anakin/liar.mp3",
      "./sound-effects/anakin/new-powers.mp3",
      "./sound-effects/anakin/no.mp3",
      "./sound-effects/anakin/not-fair.mp3",
      "./sound-effects/anakin/pledge-myself.mp3",
      "./sound-effects/anakin/sand.mp3",
      "./sound-effects/anakin/so-beautiful.mp3",
      "./sound-effects/anakin/speeder.mp3",
      "./sound-effects/anakin/stand-trial.mp3",
      "./sound-effects/anakin/take-her-from-me.mp3",
      "./sound-effects/anakin/too-many.mp3",
      "./sound-effects/anakin/unfair.mp3",
      "./sound-effects/anakin/you-will-try.mp3",
      "./sound-effects/anakin/what-have-i-done.mp3",
      "./sound-effects/obi-won/underestimate-my-power.mp3",
      "./sound-effects/yoda/suffering.mp3",
      "./sound-effects/yoda/death-sound.mp3",
      "./sound-effects/yoda/very-good.mp3",
      "./sound-effects/palpatine/deformed.mp3",
      "./sound-effects/palpatine/do-it.mp3",
      "./sound-effects/palpatine/feel-your-anger.mp3",
      "./sound-effects/palpatine/good.mp3",
      "./sound-effects/palpatine/grunt.mp3",
      "./sound-effects/palpatine/i-am-the-senate.mp3",
      "./sound-effects/palpatine/ironic.mp3",
      "./sound-effects/palpatine/kill-him.mp3",
      "./sound-effects/palpatine/kill-me.mp3",
      "./sound-effects/palpatine/no-no.mp3",
      "./sound-effects/palpatine/not-from-a-jedi.mp3",
      "./sound-effects/palpatine/once-more.mp3",
      "./sound-effects/palpatine/only-natural.mp3",
      "./sound-effects/palpatine/order.mp3",
      "./sound-effects/palpatine/taking-over.mp3",
      "./sound-effects/palpatine/too-weak.mp3",
      "./sound-effects/palpatine/too-weak-1.mp3",
      "./sound-effects/palpatine/tragedy.mp3",
      "./sound-effects/palpatine/treason.mp3",
      "./sound-effects/palpatine/unlimited-power.mp3",
      "./sound-effects/padme/suffer-and-die.mp3",
      "./sound-effects/padme/breaking-my-heart.mp3",
      "./sound-effects/padme/liberty-dies.mp3",
      "./sound-effects/padme/youve-grown.mp3",
      "./sound-effects/mace-windu/party-over.mp3",
      "./sound-effects/mace-windu/sith-lord.mp3",
      "./sound-effects/mace-windu/take-a-seat.mp3",
      "./sound-effects/mace-windu/think-so.mp3",
      "./sound-effects/mace-windu/under-arrest.mp3",
      "./sound-effects/count-dooku/double-the-fall.mp3",
      "./sound-effects/count-dooku/great-fear.mp3",
      "./sound-effects/greivous/doomed.mp3",
      "./sound-effects/greivous/fine-addition.mp3",
      "./sound-effects/greivous/general-kenobi.mp3",
      "./sound-effects/greivous/jedi-scum.mp3",
      "./sound-effects/greivous/negotiator.mp3",
      "./sound-effects/greivous/ray-shields.mp3",
      "./sound-effects/greivous/you-fool.mp3",
      "./sound-effects/obi-won/negotiations.mp3",
      "./sound-effects/obi-won/absolutes.mp3",
      "./sound-effects/obi-won/always-on-the-move.mp3",
      "./sound-effects/obi-won/archives-are-incomplete.mp3",
      "./sound-effects/obi-won/bad-feeling-about-this.mp3",
      "./sound-effects/obi-won/chosen-one.mp3",
      "./sound-effects/obi-won/death-sticks.mp3",
      "./sound-effects/obi-won/easy.mp3",
      "./sound-effects/obi-won/hate-it.mp3",
      "./sound-effects/obi-won/hello-there.mp3",
      "./sound-effects/obi-won/high-ground.mp3",
      "./sound-effects/obi-won/like-it.mp3",
      "./sound-effects/obi-won/pull-up.mp3",
      "./sound-effects/obi-won/sith-lords.mp3",
      "./sound-effects/obi-won/so-uncivilized.mp3",
      "./sound-effects/obi-won/sweating.mp3",
      "./sound-effects/obi-won/together.mp3",
      "./sound-effects/obi-won/find-us.mp3",
      "./sound-effects/obi-won/good-job.mp3",
      "./sound-effects/obi-won/another-happy-landing.mp3",
      "./sound-effects/trade-federation/all-batteries-fire.mp3",
      "./sound-effects/trade-federation/coming-through.mp3",
      "./sound-effects/trade-federation/droidekas.mp3",
      "./sound-effects/trade-federation/magnetize.mp3",
      "./sound-effects/trade-federation/promised-peace.mp3",
      "./sound-effects/trade-federation/shoot-her.mp3",
      "./sound-effects/trade-federation/victory.mp3",
      "./sound-effects/jar-jar/ah-hah.mp3",
      "./sound-effects/jar-jar/big-goober-fish.mp3",
      "./sound-effects/jar-jar/boom.mp3",
      "./sound-effects/jar-jar/exqueeze-me.mp3",
      "./sound-effects/jar-jar/hello-boyos.mp3",
      "./sound-effects/jar-jar/how-wude.mp3",
      "./sound-effects/jar-jar/i-spek.mp3",
      "./sound-effects/jar-jar/jump-jar-jar.mp3",
      "./sound-effects/jar-jar/maxi-big.mp3",
      "./sound-effects/jar-jar/meesa-back.mp3",
      "./sound-effects/jar-jar/meesa-jar-jar-binks.mp3",
      "./sound-effects/jar-jar/messa-like-dis.mp3",
      "./sound-effects/jar-jar/muy-muy.mp3",
      "./sound-effects/jar-jar/my-give-up.mp3",
      "./sound-effects/jar-jar/pee-yousa.mp3",
      "./sound-effects/jar-jar/saved-my-again.mp3",
      "./sound-effects/jar-jar/steady.mp3",
      "./sound-effects/jar-jar/stinkywhiff.mp3",
      "./sound-effects/jar-jar/very-bad.mp3",
      "./sound-effects/jar-jar/whosa-are-yousa.mp3",
      "./sound-effects/jar-jar/yelling.mp3",
      "./sound-effects/jar-jar/your-honor.mp3",
      "./sound-effects/jar-jar/bustin-with-happiness.mp3",
      "./sound-effects/jar-jar/looky-looky.mp3",
      "./sound-effects/jar-jar/so-smiling.mp3",
    ],
  },
];

module.exports = {
  content,
};
